name: Run SafeDep

on:
  workflow_dispatch: {} # allows manual trigger

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run vet
        id: vet
        uses: safedep/vet-action@v1
        with:
          cloud: true
          cloud-key: ${{ secrets.SAFEDEP_CLOUD_API_KEY }}
          cloud-tenant: ${{ secrets.SAFEDEP_CLOUD_TENANT_DOMAIN }}
          upload-sarif: false
          add-step-summary: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
